### ISSUE TITLE
Basic turtle demo and ros

### ISSUE THREAD

**Issue by sebastian-brunner** [sebastian-brunner/sebastian-brunner-test_issue_mover_with_pr#17]
trying to run the demo, i have experienced the following two items related to python, I believe:

1.
changed the init_ros_node script line 12, from
>> except Exception , e:
to
>> except Exception as e:
and gives no errors here, now.
2.
the following error appears:
ERROR - core.states.execution_state: ExecutionState with name 'init_ros_node' and id 'INIT_ROS_NODE' had an internal error: ImportError: dynamic module does not define module export function (PyInit__tf2)
Traceback (most recent call last):
  File "script.py (20)", line 2, in <module>
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/tf/__init__.py", line 28, in <module>
    from tf2_ros import TransformException as Exception, ConnectivityException, LookupException, ExtrapolationException
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/tf2_ros/__init__.py", line 38, in <module>
    from tf2_py import *
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/tf2_py/__init__.py", line 38, in <module>
    from ._tf2 import *
ImportError: dynamic module does not define module export function (PyInit__tf2)

can you help!

Originally created by pbsgoncalves  at 2019-04-11 01:45:23+00:00 (moved from RMC internal repository)

**Comment by sebastian-brunner** [comment]
Hi,

regarding your first point: `except Exception , e:` is valid in Python <= 2.7. This leads me to the question: are you maybe using Python 3?

Because, reagarding your 2nd point, ROS does not support Python 3. In any case, the stacktrace you posted stems from ROS, not RAFCON. So I am quite sure that this has nothing to to with RAFCON.

Googleing for the error message indicates that my assumption is probably right and you are trying to use ROS with Python 3, see for example [this issue](https://github.com/whoenig/crazyflie_ros/issues/82) or [this issue](https://github.com/ros/geometry2/issues/259).

I hope this helps!

Originally created by @franzlst  (mail@franzsteinmetz.de) at 2019-04-11 07:05:48+00:00 (moved from RMC internal repository)

**Comment by sebastian-brunner** [comment]
Please use python2 for ROS. Python3 is not officially supported, even not for [melodic](http://www.ros.org/reps/rep-0003.html#melodic-morenia-may-2018-may-2023).

Also see [this link](https://answers.ros.org/question/237613/how-to-define-ros-kinetic-to-use-python3-instead-of-python27/) for more information.


Originally created by @sebastian-brunner  (sebastian.brunner@dlr.de) at 2019-04-12 09:30:40+00:00 (moved from RMC internal repository)

**Comment by sebastian-brunner** [comment]
Have you resolved your issue @pbsgoncalves? we have recognized your last comment which vanished very fast. 

We assume you found out that the documentation was about an DLR internal environment. 

If you still have the issue give some more insides and check if you have confirmed the mentioned solutions of @SebastianGB and @franzlst to be in place.

Originally created by @Rbelder  at 2019-05-02 12:06:24+00:00 (moved from RMC internal repository)

**Comment by sebastian-brunner** [comment]
If you have any further questions, feel free to reopen this issue.

Originally created by @sebastian-brunner  (sebastian.brunner@dlr.de) at 2019-05-07 13:02:56+00:00 (moved from RMC internal repository)
